services:
  - type: web
    name: flask-react-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: NODE_VERSION
        value: 16.16.0
      - key: FLASK_ENV
        value: production
